# Generated by Django 4.1.2 on 2022-11-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guestbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=600)),
                ("writer", models.CharField(max_length=40)),
                ("wdate", models.DateTimeField()),
                ("contents", models.TextField()),
                ("hit", models.IntegerField()),
            ],
        ),
    ]
